shadow = false;
fading = false;
frame-opacity = 1;
corner-radius = 0;

blur: {
    method = "dual_kawase";
    strength = 2;
};

backend = "glx"
#backend = "egl"
dithered-present = false;
vsync = true;

detect-client-opacity = true;
unredir-if-possible = true
detect-transient = true;
use-damage = true;

rules: ({
  match = "window_type = 'tooltip'";
  fade = false;
  shadow = true;
  opacity = 0.75;
  full-shadow = false;
}, {
  match = "window_type = 'dock'    || "
          "window_type = 'desktop' || "
          "_GTK_FRAME_EXTENTS@";
  blur-background = false;
}, {
  match = "window_type != 'dock'";
  # shader = "my_shader.frag";
}, {
    match = "class_g = 'com.mitchellh.ghostty'  &&  "
            "focused != 1";
    opacity = 0.85;
}, {
    match = "class_g = 'st-256color'            &&  "
            "focused != 1";
    opacity = 0.85;
}, {
    match = "window_type = 'normal'";
    animations = (
        {
            triggers = [ "close", "hide" ];
            preset = "slide-out";
            direction = "right";
        },
        {
            triggers = [ "open", "show" ];
            preset = "slide-in";
            direction = "right";
        },
        {
            triggers = [ "geometry" ];
            preset = "geometry-change";
            duration = 0.5;
        },
    );
});

# `@include` directive can be used to include additional configuration files.
# Relative paths are search either in the parent of this configuration file
# (when the configuration is loaded through a symlink, the symlink will be
# resolved first). Or in `$XDG_CONFIG_HOME/picom/include`.
#
# @include "extra.conf"
