--force-device-scale-factor=1.66
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL
--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
--enable-features=UseOzonePlatform
--ozone-platform=wayland
--gtk-version=4
--enable-features=WaylandPerSurfaceScale,WaylandUiScale
